enum UserActionTypes {
  CHANGE_USERNAME = "CHANGE_USERNAME",
  CHANGE_PASSWORD = "CHANGE_PASSWORD",
  CHANGE_ACCOUNT_BALANCE = "CHANGE_ACCOUNT_BALANCE",
  CHANGE_IS_USERNAME_VALID = "CHANGE_IS_USERNAME_VALID",
  CHANGE_IS_PASSWORD_VALID = "CHANGE_IS_PASSWORD_VALID",
  CHANGE_IS_LOGIN_SUCCESSFULL = "CHANGE_IS_LOGIN_SUCCESSFULL",
  CHANGE_IS_LOGIN_ATTEMPT_STARTED = "CHANGE_IS_LOGIN_ATTEMPT_STARTED",
  CHANGE_IS_LOGOUT_ATTEMPT_STARTED = "CHANGE_IS_LOGOUT_ATTEMPT_STARTED",
  CHANGE_SELECTED_MAIN_PAGE_INDEX = "CHANGE_SELECTED_MAIN_PAGE_INDEX",
}

export const {
  CHANGE_USERNAME,
  CHANGE_PASSWORD,
  CHANGE_ACCOUNT_BALANCE,
  CHANGE_IS_USERNAME_VALID,
  CHANGE_IS_PASSWORD_VALID,
  CHANGE_IS_LOGIN_SUCCESSFULL,
  CHANGE_IS_LOGIN_ATTEMPT_STARTED,
  CHANGE_IS_LOGOUT_ATTEMPT_STARTED,
  CHANGE_SELECTED_MAIN_PAGE_INDEX,
} = UserActionTypes;
