enum UserActionTypes {
  CHANGE_USERNAME = "CHANGE_USERNAME",
  CHANGE_PASSWORD = "CHANGE_PASSWORD",
  CHANGE_ACCOUNT_BALANCE = "CHANGE_ACCOUNT_BALANCE",
  CHANGE_IS_USERNAME_VALID = "CHANGE_IS_USERNAME_VALID",
  CHANGE_IS_PASSWORD_VALID = "CHANGE_IS_PASSWORD_VALID",
  CHANGE_IS_LOGIN_SUCCESSFULL = "CHANGE_IS_LOGIN_SUCCESSFULL",
}

export const {
  CHANGE_USERNAME,
  CHANGE_PASSWORD,
  CHANGE_ACCOUNT_BALANCE,
  CHANGE_IS_USERNAME_VALID,
  CHANGE_IS_PASSWORD_VALID,
  CHANGE_IS_LOGIN_SUCCESSFULL,
} = UserActionTypes;
